"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['web.py']
DATA_FILES = ['user_dao.py']
OPTIONS = {
    "includes":["bottle","sqlite-web"],
    "iconfile":"icon.icns",
    "plist":{"CFBundleShortVersionString":"0.1.0"},
    'resources': ['./views', './static'],

}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    py_modules=["lib"]
)
